apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-api
  labels:
    app: storage-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storage-api
  template:
    metadata:
      labels:
        app: storage-api
    spec:
      containers:
      - name: consumer
        image: dreamstream/dream-stream-storage:V1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        volumeMounts:
        - name: file-writing
          mountPath: /mnt/data
      volumes:
      - name: file-writing
        persistentVolumeClaim:
          claimName: storage-claim
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: storage-claim
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi